### ISSUE TITLE
Can't get this to send code

### ISSUE THREAD

**Issue by TylerBackman** [ssayols/screenR#1]
I can't get this to send lines of code. Everything seems to load with no errors (R starts in screen), but lines of code don't appear in the R console when sent. My vimR install does send code to R inside Tmux.

My details:
CentOS Linux 7.1.1503
vimcom 1.2.5
Vim-R-plugin 1.2.5
vim 7.4.728
screen 4.01.00devel
R 3.2.0

**Comment by ssayols** [comment]
Hi Tyler,
I'd ask you to check few things:
1-is the screen window title in the R console automatically set to "RConsole"?
2-in the RConsole window, when starting R, are all these variables informed? just scroll up a little bit:
`VIMRPLUGIN_TMPDIR=/tmp/r-plugin-sergi VIMRPLUGIN_COMPLDIR=/home/sergi/.cache/Vim-R-plugin VIMINSTANCEID=homesergixRryut7EDXBMlxVlGTIm2QyA VIMRPLUGIN_SECRET=UVmyc5D1GaQXNIKMwyDx VIMEDITOR_SVRNM=VIM1 R`
3-Vim should be compiled with the +clientserver feature (check it with vim --version). Also, create in your bash shell this alias for vim: `alias vim='vim --servername VIM'`

Also, these options help in the .vimrc file (specially mapping <Space> to send a line/selection in normal and visual mode):

``` bash
    let vimrplugin_source = "~/.vim/r-plugin/screenR.vim"
    let vimrplugin_show_args = 1
    vmap <Space> <Plug>REDSendSelection
    nmap <Space> <Plug>RDSendLine
```

cheers,
Sergi

**Comment by TylerBackman** [comment]
An additional note- if I log into my computer without X forwarding, vimcom gives a notice "vimcom: There is no X Server running."

1) No- the window name I get from the C-a " command is "tbackman@hostname:~"

2) Yes, these are my variables below:

VIMRPLUGIN_TMPDIR=/tmp/r-plugin-tbackman VIMRPLUGIN_COMPLDIR=/rhome/tbackman/.cache/Vim-R-plugin VIMINSTANCEID=rhometbackmanokRNO7MmRvq0Z566fQr3b64w VIMRPLUGIN_SECRET=GSIgjhdGbkxCXjK3bofK2A VIMEDITOR_SVRNM=NoServerName R

3) Vim is compiled with clientserver and loaded with an alias exactly as you specified.

4) Here is my .vimrc:

" screen vimr integration
let vimrplugin_source = "~/.vim/r-plugin/screenR.vim"
let vimrplugin_show_args = 1
vmap <Space> <Plug>REDSendSelection
nmap <Space> <Plug>RDSendLine

" Minimum required configuration:
set nocompatible
syntax on
filetype plugin on
filetype indent on

" Press the space bar to send lines and selection to R:
vmap <Space> <Plug>RDSendSelection
nmap <Space> <Plug>RDSendLine

" start R with F2 key
map <F2> <Plug>RStart
imap <F2> <Plug>RStart
vmap <F2> <Plug>RStart

**Comment by ssayols** [comment]
The error message you get plus the VIMEDITOR_SVRNM variable set to NoServerName points that Vim doesn't run with the --servername option (regardless the alias you created). First I'd recommend you to try testing with `vim --servername x.R`

Then, as per your .vimrc, can you confirm the file ~/.vim/r-plugin/screenR.vim exists? I'd also move the first block (under " screen vimr integration) at the very end. You can remove the duplicated key mappings.

To ensure you screenR.vim gets loaded, you can try to add a debug line to the screenR.vim script so it displays a message just after loading. To do that, just add in the very beginning a print statement like this one `call RWarningMsg("loading screenR...")`

If things still don't work and you're in the mood for, I'll point you to some debugging steps:
In Normal mode Vim do:
´´´
   :echo g:rplugin_tmpdir
   :echo g:rplugin_compldir
   :echo $VIMINSTANCEID
   :echo $VIMRPLUGIN_SECRET
   :echo $VIMEDITOR_SVRNM
´´´
Then, in R do (You can manually call the function to start R within Vim with ´:call StartR("R")´):
´´´
   Sys.getenv("VIMRPLUGIN_TMPDIR")
   Sys.getenv("VIMINSTANCEID")
   Sys.getenv("VIMRPLUGIN_SECRET")
   Sys.getenv("VIMEDITOR_SVRNM")
   Sys.getenv("VIMRPLUGIN_COMPLDIR")
´´´
If the values of the variables do not match, in R do:
´´´
   detach("package:vimcom", unload = TRUE)
   Sys.setenv(VIMRPLUGIN_TMPDIR="T")    # where "T" is what Vim has echoed
   Sys.setenv(VIMINSTANCEID="I")        # where "I" is what Vim has echoed
   Sys.setenv(VIMRPLUGIN_SECRET="S")   # where "S" is what Vim has echoed
   Sys.setenv(VIMEDITOR_SVRNM="N")     # where "N" is what Vim has echoed
   Sys.setenv(VIMRPLUGIN_COMPLDIR="C") # where "C" is what Vim has echoed
   library(vimcom)
´´´
Let me know whether it worked.
cheers,
Sergi

**Comment by ssayols** [comment]
Hi Tyler, any news? can you confirm vim was running with the --servername option and the vimrplugin_source variable in your .vimrc referring to a valid file?
